CREATE DATABASE anonimos;

USE anonimos;

CREATE TABLE person (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc LONG NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL
);


CREATE TABLE alcoholic (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc LONG NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL,
sessions INT NOT NULL,
nickname VARCHAR(100) NOT NULL
);

CREATE TABLE psychologist(
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc LONG NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL,
graduation YEAR NOT NULL,
days INT NOT NULL,
supportedsessions INT NOT NULL,
salary INT NOT NULL
);

CREATE TABLE services (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc LONG NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL,
salary DOUBLE NOT NULL,
cleanup INT NOT NULL
);

CREATE TABLE administrador(
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc LONG NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL
);

INSERT INTO usuario VALUES (1, 'jose', 'jose2003', 'HOLA');