CREATE DATABASE anonimos;

USE anonimos;

CREATE TABLE person (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc BIGINT UNIQUE NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL
);

INSERT INTO person (allname, cc, birthdate, city)
VALUES ('Nombre Apellido', 1234567892, '2023-09-25', 'Ciudad de Nacimiento');
SELECT * FROM person;

CREATE TABLE alcoholic (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc BIGINT UNIQUE NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL,
sessions INT NOT NULL,
nickname VARCHAR(100) NOT NULL
);

CREATE TABLE psychologist(
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc BIGINT UNIQUE NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL,
graduation DATE NOT NULL,
days INT NOT NULL,
supportedsessions INT NOT NULL,
salary INT NOT NULL
);

CREATE TABLE services (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc BIGINT UNIQUE NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL,
salary DOUBLE NOT NULL,
cleanup INT NOT NULL
);

CREATE TABLE administrador(
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc BIGINT UNIQUE NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL
);

CREATE TABLE administrador(
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
allname VARCHAR(100) NOT NULL,
cc BIGINT UNIQUE NOT NULL,
birthdate DATE NOT NULL,
city VARCHAR(100) NOT NULL
);
SELECT * FROM administrador;
INSERT INTO administrador (allname, cc, birthdate, city)
VALUES ('joccse', 1235627892 , '2023-09-25', 'Ciudad de Nacimiento');